modLoader="javafml"
loaderVersion="[55,)"
license="All Rights Reserved"

[[mods]]
modId="ezi"
version="2.0.0"
displayName="EZI - Easy Items Index"
authors="knoxhack"
description='''
Easy access to items, recipes, usages, and favorites with dark mode, search, and filters.
'''

[[dependencies.ezi]]
modId="forge"
mandatory=true
versionRange="[55.0.0,)"
ordering="NONE"
side="CLIENT"